### PR TITLE
added "special prepare when Nvidia Jetson Nano"

### PR DESCRIPTION
**Pull request by bavarianledger**
Disables GUI/X11 login to make sure that you can login after rebooting.

### CODE REVIEW

**Comment by openoms** [comment]
Do I understand it right, that this would allow logging in to the node if there is a physical access. See evil maid attack.
I think it is an intentional security decision to not allow login from the node with a keyboard plugged in, only ssh.
Were you able to ssh in your case?

**Comment by bavarianledger** [comment]
Without this patch neither login via ssh nor keyboard/screen was possible. 
With the patch the HDMI-output is text based, allowing you to see the `./00raspiblitz.sh` output.

**Comment by openoms** [comment]
Is this on ubuntu bionic? 
Can you tell what is original value here instead of the multi-user.target?
I just need to understand it a bit more about what is happening with this line.
I did not experience such a problem yet, but the aarch64 is the least tested by me. My poor rock64 has bigger problems with crunching numbers.
I am running Ubuntu bionic in a VM X86_64. No problem with SSH or anything like this.

**Comment by bavarianledger** [comment]
Yes, it's bionic, but a customized [image](https://developer.nvidia.com/embedded/dlc/jetson-nano-dev-kit-sd-card-image) from [Nvidia](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write).

To switch to text-only mode:
`sudo systemctl set-default multi-user.target`
To set it back to graphical mode:
`sudo systemctl set-default graphical.target`

**Comment by openoms** [comment]
> Yes, it's bionic, but a customized [image](https://developer.nvidia.com/embedded/dlc/jetson-nano-dev-kit-sd-card-image) from [Nvidia](https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit#write).
> 
> To switch to text-only mode:
> `sudo systemctl set-default multi-user.target`
> To set it back to graphical mode:
> `sudo systemctl set-default graphical.target`

Right that makes more sense. The repos I am suing so far definitely are text mode only, so I gues there would be no difference running that command. 
The Jetson Nano is quite GPU heavy so I guess that is why the focus is on graphics.
Good to know that, thank you!

If I run it on my Odroid XU4 (armV7l, 32bit):
`$ sudo systemctl set-default multi-user.target`
get the output:
`Created symlink /etc/systemd/system/default.target → /lib/systemd/system/multi-user.target.`
And seemingly no difference.

**Comment by openoms** [comment]
There is a pull request waiting to be merged to @rootzoll master from this branch so will wait to merge this until I can test on the only aarch64 board I have, the Rock64. A new Armbian kernel is said to be solving it`s memory clock issues, so having my hopes up!

**Comment by openoms** [comment]
You can specify more to your release by grepping info from `uname -a` (https://www.liquidweb.com/kb/how-to-check-the-kernel-version-in-linux-ubuntu-centos/)

For my Rock64 it shows:
`Linux rock64 4.4.174-rockchip64 #6 SMP Sun Feb 10 10:43:16 CET 2019 aarch64 aarch64 aarch64 GNU/Linux`

Can you paste it for the Jetson Nano?

**Comment by bavarianledger** [comment]
`Linux rockpro64 4.4.132-1075-rockchip-ayufan-ga83beded8524 #1 SMP Thu Jul 26 08:22:22 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by bavarianledger** [comment]
`Linux XXX 4.9.140-tegra #1 SMP PREEMPT Wed Mar 13 00:32:22 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by openoms** [comment]
> `Linux XXX 4.9.140-tegra #1 SMP PREEMPT Wed Mar 13 00:32:22 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux`

I think it would be the best to introduce a variable to identify the Jetson Nano specifically by processor:
`isNvidia=$(uname -a | grep -c 'tegra')`
or
`isNvidia=$(uname -p | grep -c 'tegra')`  --> please check what returns `tegra` on Jetson Nano

Then if statement can be changed to:
`if [ ${isNvidia} -eq 1 ] ; then`

**Comment by bavarianledger** [comment]
Great idea.
I've updated the PR accordingly.

**Comment by openoms** [comment]
merged now, thanks

**Pull request merged**
